resources:
  - name: gcp_pipeline
    type: GitRepo
    configuration:
      gitProvider: vijay_github
      path: vijayreddy1991/GCP_Installer
      
pipelines:
  - name: GCP_installer
    steps:
      - name: Spin_up_GCP
        type: Bash
        configuration:
          affinityGroup: debain 
          priority: 0
          timeoutSeconds: 50000
#           nodePool: ubuntu_16
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: gcp_key
          inputResources:
            - name: gcp_pipeline
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute: 
            - pwd
            - terraform --version
            - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
            - Place=$(pwd)
            - echo path=$Path  
            - pushd ~/.ssh
            - ls -la
            - popd
            - printenv
            - pushd $res_gcp_pipeline_resourcePath
            - replace_envs $PWD/variable.tf
            - terraform init            
            - PWD=$(pwd)
            - echo PWD=$PWD
            - echo "$int_gcp_key_jsonKey" > gcp.json
            - ls -la            
            - terraform apply -auto-approve -var-file="$PWD/gcp.json"
            - terraform output ip
            - vijay_ip_address=$(terraform output ip)
            - echo "$vijay_ip_address"          
            - add_pipeline_variables vijay_ip_address=$vijay_ip_address
            - add_pipeline_files $PWD/terraform.tfstate jfrog_pipeline
            - add_pipeline_files ~/.ssh/id_rsa jfrog_pipeline
            - popd

      - name: GCP_installer_ubuntu
        type: Bash
        configuration:
          affinityGroup: debain
          priority: 0
          timeoutSeconds: 50000
#           nodePool: ubuntu_16
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: gcp_key
            - name: ART_keys
            - name: art
          inputSteps:
            - name: Spin_up_GCP
          inputResources:
            - name: gcp_pipeline            
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - printenv
            - restore_pipeline_files jfrog_pipeline ~/.ssh/id_rsa
            - pushd $res_gcp_pipeline_resourcePath
            - PWD=$(pwd)
            - echo $PWD
            - replace_envs $PWD/pipeline_installer.sh
            - cat $PWD/pipeline_installer.sh
            - echo $vijay_ip_address
            - chmod 777 "$PWD"/pipeline_installer.sh
            - chmod 777 "$PWD"/test.sh
            - chmod 400 ~/.ssh/id_rsa
            - which ssh
            - scp -i ~/.ssh/id_rsa $PWD/pipeline_installer.sh test.sh vijay@$vijay_ip_address:~
            - ssh -i ~/.ssh/id_rsa vijay@$vijay_ip_address ls
            - ssh -i ~/.ssh/id_rsa vijay@$vijay_ip_address "sudo ./pipeline_installer.sh"
            - ssh -i ~/.ssh/id_rsa vijay@$vijay_ip_address "sudo ./test.sh"

      - name: Destroy_GCP_machines
        type: Bash
        configuration:
          affinityGroup: debain 
          priority: 0
          timeoutSeconds: 50000
#           nodePool: ubuntu_16
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: gcp_key
          inputSteps:
            - name: GCP_installer_ubuntu
          inputResources:
            - name: gcp_pipeline
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute: 
            - pushd $res_gcp_pipeline_resourcePath
            - echo $PWD
            - echo "$int_gcp_key_jsonKey" > gcp.json           
            - echo "$vijay_ip_address"
            - terraform init
            - restore_pipeline_files jfrog_pipeline $PWD/terraform.tfstate
            - ls -la
            - terraform destroy -auto-approve -var-file="$PWD/gcp.json"
            - popd
